// Estrutura de dados para todas as matérias e questões
const flashcardsData = {
    portugues: {
        name: "Língua Portuguesa",
        questions: [
            { question: "O que é um texto dissertativo?", answer: "É um texto que apresenta uma opinião ou argumento sobre um tema." },
            { question: "Qual é o objetivo de um texto narrativo?", answer: "Contar uma história com personagens, tempo e espaço definidos." },
            { question: "Qual é a função do pronome relativo?", answer: "Substituir um termo anterior e iniciar uma oração subordinada." },
            { question: "O que é coesão textual?", answer: "É a conexão entre as partes de um texto para garantir continuidade." },
            { question: "O que é coerência textual?", answer: "É a lógica e o sentido do texto como um todo." },
            { question: "Qual a diferença entre parônimos e homônimos?", answer: "Parônimos têm escrita e som parecidos; homônimos têm som igual." },
            { question: "O que são pronomes átomos?", answer: "São pronomes que não têm tonicidade própria (me, te, se, nos...)." },
            { question: "O que é regência verbal?", answer: "É a relação entre um verbo e os termos que o completam." },
            { question: "Quando se usa o ponto e vírgula?", answer: "Para separar orações com certa independência ou itens complexos em lista." },
            { question: "Qual é a função da vírgula?", answer: "Separar elementos, orações e indicar pausas no texto." },
            { question: "O que é uma oração subordinada?", answer: "É uma oração que depende de outra para ter sentido completo." },
            { question: "O que é uma oração coordenada?", answer: "É uma oração que tem sentido completo e se liga a outra." },
            { question: "Qual é a diferença entre oração e período?", answer: "Oração tem verbo; período é uma ou mais orações completas." },
            { question: "Quando se usa crase?", answer: "Quando ocorre a fusão da preposição 'a' com o artigo definido 'a'." },
            { question: "O que é colocação pronominal?", answer: "É a posição dos pronomes oblíquos em relação ao verbo." },
            { question: "O que é ambiguidade?", answer: "É a duplicidade de sentido numa frase." },
            { question: "O que é verbo de ligação?", answer: "É o verbo que liga o sujeito a uma característica (ex: ser, estar)." },
            { question: "Qual é a função do sujeito oculto?", answer: "É aquele que não aparece na oração, mas é identificado pelo contexto." },
            { question: "Qual é o sujeito indeterminado?", answer: "É aquele que não se sabe ou não se quer identificar." },
            { question: "O que é frase?", answer: "Enunciado com sentido completo, podendo ou não ter verbo." },
            { question: "O que é uma oração reduzida?", answer: "É uma oração subordinada que não se inicia por conjunção." },
            { question: "Como se identifica a voz passiva?", answer: "O sujeito recebe a ação verbal." },
            { question: "O que é um predicado verbal?", answer: "É aquele cujo núcleo é um verbo de ação." },
            { question: "O que é um predicado nominal?", answer: "É aquele cujo núcleo é um nome (estado ou característica do sujeito)." },
            { question: "O que é um predicado verbo-nominal?", answer: "É aquele que possui dois núcleos: um verbo e um nome." },
            { question: "Qual é a estrutura básica da oração?", answer: "Sujeito + verbo + complementos." },
            { question: "O que é a norma culta da língua?", answer: "É a forma gramaticalmente correta, usada em contextos formais." },
            { question: "O que é o Manual da Presidência da República?", answer: "É o guia oficial de redação para órgãos públicos." },
            { question: "Qual é o objetivo da redação oficial?", answer: "Clareza, concisão, formalidade e impessoalidade." },
            { question: "Como deve ser a linguagem da redação oficial?", answer: "Impessoal, clara e objetiva." },
            { question: "O que é paralelismo sintático?", answer: "É a simetria na estrutura das frases." },
            { question: "O que é substituição lexical?", answer: "Trocar uma palavra por sinônimo ou termo equivalente." },
            { question: "O que é uma anáfora?", answer: "Referência a um termo anterior no texto." },
            { question: "O que é catáfora?", answer: "Referência a um termo que ainda será mencionado." },
            { question: "O que é coesão referencial?", answer: "É a retomada de ideias ou termos no texto." },
            { question: "O que é coesão sequencial?", answer: "É a organização lógica entre as partes do texto." },
            { question: "Qual é a diferença entre linguagem denotativa e conotativa?", answer: "Denotativa é literal; conotativa é figurada." },
            { question: "Quando se usa ponto final?", answer: "Para encerrar uma oração declarativa." },
            { question: "O que indica o ponto de interrogação?", answer: "Uma pergunta direta." },
            { question: "Quando se usa reticências?", answer: "Para indicar interrupção ou continuação de ideia." },
            { question: "Quando se usa os dois-pontos?", answer: "Antes de uma explicação ou citação." },
            { question: "Como se caracteriza a linguagem formal?", answer: "Regras gramaticais, vocabulário técnico, sem gírias." },
            { question: "Qual o papel do sujeito composto?", answer: "Dois ou mais núcleos realizando a ação verbal." },
            { question: "O que é tempo verbal?", answer: "Indica quando a ação verbal acontece." },
            { question: "O que é modo verbal?", answer: "Expressa a atitude do falante (indicativo, subjuntivo, imperativo)." },
            { question: "O que é um verbo irregular?", answer: "É aquele que não segue o modelo padrão de conjugação." },
            { question: "O que é verbo transitivo?", answer: "É o verbo que exige complemento (objeto direto ou indireto)." },
            { question: "O que é verbo intransitivo?", answer: "Não exige complemento." },
            { question: "Qual a diferença entre adjunto e complemento?", answer: "Adjunto acrescenta; complemento é necessário." },
            { question: "O que é predicativo do sujeito?", answer: "É a característica atribuída ao sujeito por meio do verbo de ligação." },
            { question: "O que é sujeito elíptico?", answer: "Sujeito que não aparece, mas é identificado pelo contexto." },
            { question: "O que é período composto?", answer: "Frase com duas ou mais orações." },
            { question: "O que é conjunção?", answer: "Palavra que liga orações ou termos semelhantes." },
            { question: "O que são interjeições?", answer: "Palavras que expressam emoções ou sentimentos." },
            { question: "O que é um advérbio?", answer: "Palavra que modifica verbo, adjetivo ou outro advérbio." },
            { question: "O que é uma preposição?", answer: "Palavra que liga dois termos estabelecendo relação entre eles." },
            { question: "O que é locução verbal?", answer: "Conjunto de dois ou mais verbos com valor de um só." },
            { question: "O que é sujeito indeterminado?", answer: "Quando o agente da ação não é identificado." },
            { question: "Qual a diferença entre 'por que' e 'porque'?", answer: "'Por que' é usado em perguntas; 'porque' em respostas." },
            { question: "O que é sujeito inexistente?", answer: "Quando o verbo é impessoal (ex: 'faz frio')." },
            { question: "O que é polissemia?", answer: "Quando uma palavra tem vários significados." },
            { question: "O que é denotação?", answer: "Uso literal da linguagem." },
            { question: "O que é conotação?", answer: "Uso figurado da linguagem." },
            { question: "Qual é a função da coesão lexical?", answer: "Evitar repetições, usando sinônimos ou expressões equivalentes." },
            { question: "O que é sentido figurado?", answer: "Quando a palavra é usada fora do seu sentido comum." },
            { question: "O que é aposto?", answer: "Termo que explica ou especifica outro, geralmente separado por vírgulas." },
            { question: "O que é vocativo?", answer: "Chamamento ou interpelação direta ao interlocutor." },
            { question: "O que são advérbios de intensidade?", answer: "Indicam grau da ação, como 'muito', 'demais', 'tão'." },
            { question: "O que é pleonasmo?", answer: "Repetição de ideias para reforço de significado." },
            { question: "O que é hipérbole?", answer: "Exagero intencional na expressão de uma ideia." },
            { question: "O que é antítese?", answer: "Oposição de ideias numa mesma frase." },
            { question: "O que é paradoxo?", answer: "Contradição aparente entre termos que expressam uma ideia." },
            { question: "O que é elipse?", answer: "Omissão de um termo facilmente subentendido." },
            { question: "O que é zeugma?", answer: "Tipo de elipse em que se omite um termo já mencionado." },
            { question: "O que é metonímia?", answer: "Substituição de uma palavra por outra com relação próxima." },
            { question: "O que é prosopopeia?", answer: "Atribuição de características humanas a seres inanimados." },
            { question: "O que é perifrase?", answer: "Uso de expressão que substitui um nome próprio ou comum." },
            { question: "O que é paródia?", answer: "Reinterpretação crítica ou humorística de texto ou obra." },
            { question: "O que é paráfrase?", answer: "Reescrita de um texto mantendo o sentido original." },
            { question: "O que é coesão por elipse?", answer: "Ligação textual com omissão de elementos já conhecidos." },
            { question: "O que é discurso indireto livre?", answer: "Mistura do discurso direto com o indireto sem uso de verbos declarativos." },
            { question: "O que são figuras de som?", answer: "Recursos como aliteração, assonância e onomatopeia." },
            { question: "O que é parônimia contextual?", answer: "Uso de palavras parônimas com sentidos distintos pelo contexto." },
            { question: "O que é predicado oculto?", answer: "Quando a ação está implícita e não declarada." },
            { question: "O que é sujeito composto por justaposição?", answer: "Quando dois ou mais termos formam o sujeito sem conectivo." }
        ]
    },
    
    informatica: {
        name: "Noções de Informática",
        questions: [
           { question: "O que é hardware?", answer: "Parte física do computador." },
            { question: "O que é software?", answer: "Conjunto de programas e sistemas usados no computador." },
            { question: "Qual é a função do sistema operacional?", answer: "Gerenciar os recursos do computador." },
            { question: "O que é o Windows 10?", answer: "Sistema operacional da Microsoft." },
            { question: "Qual é o atalho para copiar no Windows?", answer: "Ctrl + C." },
            { question: "Qual é o atalho para colar no Windows?", answer: "Ctrl + V." },
            { question: "O que é um antivirus?", answer: "Programa que protege o computador contra ameaças." },
            { question: "Para que serve um firewall?", answer: "Controlar o tráfego de dados entre redes." },
            { question: "O que é rede de computadores?", answer: "Conjunto de dispositivos conectados para trocar informações." },
            { question: "O que é uma LAN?", answer: "Rede local, usada em espaços pequenos (ex: escritório)." },
            { question: "O que é uma WAN?", answer: "Rede de longa distância (ex: internet)." },
            { question: "O que é endereço IP?", answer: "Identificação numérica de um dispositivo em uma rede." },
            { question: "Para que serve o navegador?", answer: "Acessar páginas da internet." },
            { question: "Exemplo de navegador de internet:", answer: "Google Chrome." },
            { question: "O que é URL?", answer: "Endereço de um site na internet." },
            { question: "O que é phishing?", answer: "Golpe digital para roubar dados." },
            { question: "O que é backup?", answer: "Cópia de segurança dos dados." },
            { question: "O que é um pendrive?", answer: "Dispositivo portátil de armazenamento." },
            { question: "Para que serve o Microsoft Word?", answer: "Criar e editar textos." },
            { question: "Qual é a extensão padrão do Word?", answer: ".docx" },
            { question: "Para que serve o Microsoft Excel?", answer: "Criar planilhas e fazer cálculos." },
            { question: "O que é uma célula no Excel?", answer: "Interseção entre linha e coluna." },
            { question: "Como iniciar uma fórmula no Excel?", answer: "Com sinal de igual (=)." },
            { question: "O que faz a função SOMA no Excel?", answer: "Soma valores numéricos." },
            { question: "Para que serve o PowerPoint?", answer: "Criar apresentações de slides." },
            { question: "O que é o LibreOffice?", answer: "Pacote de escritório gratuito." },
            { question: "O que é o Google Workspace?", answer: "Conjunto de ferramentas Google para produtividade." },
            { question: "Exemplos do Google Workspace:", answer: "Gmail, Drive, Docs, Sheets." },
            { question: "O que é o Google Docs?", answer: "Editor de texto online." },
            { question: "Para que serve o Google Sheets?", answer: "Planilhas online." },
            { question: "O que é computação em nuvem?", answer: "Uso de dados e programas pela internet." },
            { question: "Vantagem da nuvem:", answer: "Acesso remoto a arquivos." },
            { question: "O que é um dado?", answer: "Informação bruta, sem tratamento." },
            { question: "O que é uma informação?", answer: "Dado tratado e útil." },
            { question: "O que é banco de dados?", answer: "Conjunto organizado de dados." },
            { question: "O que é BI (Business Intelligence)?", answer: "Análise de dados para decisões estratégicas." },
            { question: "O que é um arquivo?", answer: "Conjunto de dados armazenado." },
            { question: "O que é um drive?", answer: "Dispositivo de armazenamento (ex: HD, SSD)." },
            { question: "O que é um atalho?", answer: "Caminho rápido para acessar programas." },
            { question: "O que é formatação de texto?", answer: "Alteração de aparência do texto (fonte, cor etc.)." },
            { question: "O que é planilha eletrônica?", answer: "Arquivo com linhas e colunas para cálculos." },
            { question: "O que são métricas em dados?", answer: "Unidades de medida para análise." },
            { question: "O que é a transformação de dados?", answer: "Conversão de dados brutos em úteis." },
            { question: "O que é análise de dados?", answer: "Processo de interpretação de dados." },
            { question: "Para que serve o Power BI?", answer: "Ferramenta de visualização de dados." },
            { question: "O que é segurança da informação?", answer: "Proteção dos dados contra acesso indevido." },
            { question: "O que é senha forte?", answer: "Senha com letras, números e símbolos." },
            { question: "O que é criptografia?", answer: "Codificação de dados para segurança." },
            { question: "O que é spam?", answer: "Mensagem eletrônica indesejada." },
            { question: "O que é o CADIN?", answer: "Cadastro de inadimplentes do setor público." },
            { question: "O que é sistema operacional Linux?", answer: "Sistema de código aberto usado em servidores e PCs." },
            { question: "O que é RAM?", answer: "Memória de acesso aleatório usada pelo sistema para operações temporárias." },
            { question: "O que é ROM?", answer: "Memória de leitura com dados permanentes no sistema." },
            { question: "O que é SSD?", answer: "Unidade de armazenamento mais rápida que o HD tradicional." },
            { question: "O que é protocolo HTTP?", answer: "Protocolo usado na transmissão de dados da web." },
            { question: "O que é HTTPS?", answer: "Versão segura do protocolo HTTP com criptografia." },
            { question: "Para que serve o Ctrl + T no navegador?", answer: "Abrir nova guia." },
            { question: "O que é IP dinâmico?", answer: "Endereço IP que muda a cada conexão." },
            { question: "O que é IP fixo?", answer: "Endereço IP que permanece o mesmo sempre." },
            { question: "O que é resolução de tela?", answer: "Quantidade de pixels exibidos na tela." },
            { question: "O que é DNS?", answer: "Sistema que traduz nomes de sites para IPs." },
            { question: "O que é hotspot?", answer: "Ponto de acesso Wi-Fi." },
            { question: "O que é multitarefa?", answer: "Capacidade de executar vários programas ao mesmo tempo." },
            { question: "O que é planilha em nuvem?", answer: "Planilha acessada e editada online." },
            { question: "O que é comando 'Salvar Como'?", answer: "Cria uma nova versão do arquivo com novo nome ou local." },
            { question: "O que é phishing por e-mail?", answer: "Tentativa de roubo de dados via mensagens falsas." },
            { question: "O que é autenticação em dois fatores?", answer: "Segurança extra exigindo dois meios de verificação." },
            { question: "O que é formato PDF?", answer: "Formato de documento portátil, ideal para leitura e impressão." },
            { question: "O que é modo de compatibilidade no Word?", answer: "Ajusta recursos para versões anteriores do programa." },
            { question: "O que é hiperlink?", answer: "Link que direciona para outro conteúdo ou site." },
            { question: "O que é pasta (diretório)?", answer: "Local onde arquivos são armazenados." },
            { question: "Qual a função do atalho Ctrl + Z?", answer: "Desfazer a última ação." },
            { question: "O que é cloud computing?", answer: "Computação baseada em serviços online." },
            { question: "O que é formatação de disco?", answer: "Preparação do disco rígido para receber dados." },
            { question: "O que é planilha eletrônica?", answer: "Programa usado para cálculos e organização de dados." },
            { question: "O que é malware?", answer: "Programa malicioso criado para prejudicar o sistema." },
            { question: "O que é spyware?", answer: "Programa espião que coleta dados do usuário." },
            { question: "O que é download?", answer: "Ação de transferir arquivos da internet para o computador." },
            { question: "O que é upload?", answer: "Enviar arquivos do computador para a internet." },
            { question: "O que é navegador padrão?", answer: "Navegador usado automaticamente pelo sistema." },
            { question: "O que é cookies?", answer: "Arquivos que armazenam informações do usuário em sites." },
            { question: "O que é cache?", answer: "Memória usada para armazenar dados temporários." },
            { question: "O que é drive C:?", answer: "Partição principal do sistema no Windows." },
            { question: "O que é o atalho Ctrl + P?", answer: "Imprimir o documento atual." }
        ]
    },
    
    logica: {
        name: "Raciocínio Lógico",
        questions: [
          { question: "O que é uma proposição?", answer: "É uma frase que pode ser verdadeira ou falsa." },
            { question: "O que é uma proposição simples?", answer: "Aquela com apenas uma ideia." },
            { question: "O que é uma proposição composta?", answer: "Aquela formada por duas ou mais proposições simples." },
            { question: "Qual é o símbolo da conjunção (e)?", answer: "∧" },
            { question: "Qual é o símbolo da disjunção (ou)?", answer: "∨" },
            { question: "Qual é o símbolo da condicional (se... então)?", answer: "→" },
            { question: "Qual é o símbolo da bicondicional (se e somente se)?", answer: "↔" },
            { question: "O que é negação de uma proposição?", answer: "É a afirmação contrária." },
            { question: "Negação de 'João estuda':", answer: "'João não estuda.'" },
            { question: "Qual é o valor lógico da conjunção verdadeira?", answer: "Somente se as duas forem verdadeiras." },
            { question: "Como funciona a disjunção?", answer: "É falsa apenas se as duas forem falsas." },
            { question: "O que é argumento válido?", answer: "Quando a conclusão é consequência das premissas." },
            { question: "O que é tabela-verdade?", answer: "Tabela que mostra todos os valores lógicos possíveis." },
            { question: "O que é equivalência lógica?", answer: "Duas proposições com o mesmo valor lógico." },
            { question: "Equivalente de 'Se A, então B':", answer: "'Se não B, então não A.'" },
            { question: "O que é uma inferência lógica?", answer: "Conclusão baseada em premissas." },
            { question: "O que é silogismo?", answer: "Raciocínio com duas premissas e uma conclusão." },
            { question: "O que é o princípio da não contradição?", answer: "Uma proposição não pode ser verdadeira e falsa ao mesmo tempo." },
            { question: "O que é conjunto?", answer: "Coleção de elementos." },
            { question: "Símbolo de inclusão (pertence):", answer: "∈" },
            { question: "O que é interseção de conjuntos?", answer: "Elementos comuns a dois conjuntos." },
            { question: "O que é união de conjuntos?", answer: "Todos os elementos de dois conjuntos." },
            { question: "O que é subconjunto?", answer: "Conjunto cujos elementos estão em outro." },
            { question: "O que é matriz?", answer: "Tabela de números dispostos em linhas e colunas." },
            { question: "O que é sequência lógica?", answer: "Ordem lógica entre elementos ou números." },
            { question: "O que é proposição verdadeira?", answer: "Aquela que corresponde à realidade ou lógica." },
            { question: "O que é proposição falsa?", answer: "Aquela que não corresponde à realidade." },
            { question: "O que é o valor lógico de uma proposição?", answer: "Indicação se é verdadeira (V) ou falsa (F)." },
            { question: "O que é tabela verdade da condicional?", answer: "É falsa apenas se o antecedente for verdadeiro e o consequente, falso." },
            { question: "O que é negação da conjunção (p ∧ q)?", answer: "¬p ∨ ¬q." },
            { question: "O que é diagrama de Venn?", answer: "Representação visual de conjuntos." },
            { question: "O que é conjunto universo?", answer: "Conjunto que contém todos os elementos possíveis." },
            { question: "O que é complemento de um conjunto?", answer: "Elementos do universo que não pertencem ao conjunto." },
            { question: "O que é raciocínio dedutivo?", answer: "Parte do geral para o particular." },
            { question: "O que é raciocínio indutivo?", answer: "Parte do particular para o geral." },
            { question: "O que é a lógica formal?", answer: "Estudo das formas de raciocínio válidas." },
            { question: "O que é negação da disjunção (p ∨ q)?", answer: "¬p ∧ ¬q." },
            { question: "O que é equivalência lógica da bicondicional?", answer: "(p → q) ∧ (q → p)." },
            { question: "O que é sequência numérica?", answer: "Conjunto de números com padrão ou lógica." },
            { question: "O que é lógica de argumentação?", answer: "Organização de ideias para demonstrar uma conclusão." },
            { question: "O que é contradomínio de uma função?", answer: "Conjunto de possíveis saídas de uma função." },
            { question: "O que é análise combinatória?", answer: "Técnicas para contar possibilidades." },
            { question: "O que é permutação simples?", answer: "Arranjo de elementos sem repetição." },
            { question: "O que é arranjo simples?", answer: "Agrupamento com ordem diferente." },
            { question: "O que é princípio da adição?", answer: "Soma das possibilidades de eventos excludentes." },
            { question: "O que é princípio da multiplicação?", answer: "Produto das possibilidades de eventos consecutivos." },
            { question: "O que é probabilidade?", answer: "Chance de ocorrência de um evento." },
            { question: "O que é evento complementar?", answer: "O que falta para o evento certo acontecer." },
            { question: "O que é disjunção exclusiva?", answer: "Quando apenas uma proposição pode ser verdadeira." },
            { question: "O que é raciocínio abdutivo?", answer: "Inferência a partir de hipóteses plausíveis." },
            { question: "O que é argumento inválido?", answer: "Conclusão que não decorre das premissas." },
            { question: "O que é tautologia?", answer: "Proposição sempre verdadeira." },
            { question: "O que é contradição?", answer: "Proposição sempre falsa." },
            { question: "O que é contingência?", answer: "Proposição que pode ser verdadeira ou falsa." },
            { question: "O que é negação da bicondicional (p ↔ q)?", answer: "(p ∧ ¬q) ∨ (¬p ∧ q)" },
            { question: "O que é modus ponens?", answer: "Se p → q e p é verdadeiro, então q também é." },
            { question: "O que é modus tollens?", answer: "Se p → q e q é falso, então p é falso." },
            { question: "O que é transitividade lógica?", answer: "Se p → q e q → r, então p → r." },
            { question: "O que é contrapositiva de p → q?", answer: "¬q → ¬p." },
            { question: "O que é equivalência de ¬(p ∨ q)?", answer: "¬p ∧ ¬q (Lei de De Morgan)." }
        ]
    }
};

/*
COMO ADICIONAR NOVAS MATÉRIAS E QUESTÕES:

1. Para adicionar uma nova matéria, adicione um novo objeto seguindo este padrão:
   
   novaMateria: {
       name: "Nome Completo da Matéria",
       questions: [
           {
               question: "Texto da pergunta",
               answer: "Texto da resposta"
           },
           // Adicione quantas questões quiser
       ]
   }

2. Para adicionar questões a uma matéria existente, basta adicionar novos objetos
   no array 'questions' da matéria correspondente.

3. Use sempre IDs em letras minúsculas, sem espaços ou caracteres especiais.
*/